# Use the official Node.js image as the base image
FROM node:24-alpine AS development

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and pnpm-lock.yaml (if exists) to install deps
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Start the application in development mode
CMD ["npm", "run", "start:dev"]